Add support for project-wide C++ compilation flags for libclang
facebook/nuclide pull request #1012
Opened 2017-02-02 20:50 UTC by AlexTalks

Close #916 

This adds support for providing a `nuclide_clang_flags.json` file in the project root, in which compilation flags and include paths needed for libclang (such as system header include paths) can be provided.  In this file can be provided `copts` (flags to include for each translation unit), `nocopts` (flags to filter out for each translation unit), and `includes` (paths to be added as `-isystem` includes).

2017-02-02 21:59 UTC, AlexTalks commented
@hansonw I figure you're the right person to notify about this?

2017-02-02 22:50 UTC, hansonw commented
Nice, this is cool! I'm a bit reluctant to add a one-off configuration file for this (ideally Nuclide should have one definitive file for project-level configuration), but since we don't yet have a plan for that I'm happy to take this for now. Just keep in mind that if we ever create a `.nucliderc` or similar we will probably migrate this over :)

cc @a20012251, this may be useful for what you're working on too

I'll find some time to review the code in detail, but some bikeshedding first ;)

- Maybe we should make the file 'hidden', as is the standard for most configuration files. Perhaps also make the naming a bit more generic, i.e. `.nuclide_clang_config.json`.
- I think it's a bit redundant to have both extra flags and extra includes, when one is a special case of the other. Plus this adds ambiguity in terms of the ordering. Can we just let people add the `-isystem` to their flags manually to simplify the API?
- `copts` and `nocopts` are a bit cryptic. How about `extra_flags` and `exclude_flags`?

So in summary the file would look like `{"extra_flags": [...], "exclude_flags": [...]}`.

2017-02-02 22:57 UTC, AlexTalks commented
@hansonw sure!  sounds reasonable about moving to a standard `.nucliderc` at some point.

As for the naming, I tried to follow conventions set by Buck and Bazel, though Buck doesn't have the `nocopts` feature so I stuck with Bazel's naming.  In keeping more in line with Buck's naming however, I could just use `{ "compiler_flags": [..], "exclude_compiler_flags": [..] }` if that makes more sense.

2017-02-02 23:03 UTC, hansonw commented
Actually I see in your code that you already used `extraCompilerFlags` and `ignoredCompilerFlags`.. I like those, so let's be consistent? `{"extra_compiler_flags": [], "ignored_compiler_flags": []}` then

2017-02-02 23:13 UTC, hansonw requested changes
Looks good overall!

2017-02-02 23:13 UTC, hansonw commented on pkg/nuclide-clang-rpc/lib/ClangFlagsManager.js
> +    let finalFlags = originalFlags.slice(0);
Nitpick: the slice is unnecessary. we can write this block in the functional style:

```
return originalFlags
  .filter(flag => ignoredCompilerFlags.indexOf(flag) === -1)
  .concat(extraCompilerFlags);
```

2017-02-02 23:13 UTC, hansonw commented on pkg/nuclide-clang-rpc/lib/ClangFlagsManager.js
> +    const extraCompilerFlags = projectFlags.extraCompilerFlags.flags || [];
After changing these to plain arrays the `|| []` should be unnecessary

2017-02-02 23:13 UTC, hansonw commented on pkg/nuclide-clang-rpc/lib/ClangFlagsManager.js
> +      const extraCompilerFlags = {flags: [], rawData: null, flagsFile};
As mentioned above, I'd just leave these as the raw arrays.
Also it's probably a good idea to make these fields optional, so make sure you handle the case where they're null.

2017-02-02 23:13 UTC, hansonw commented on pkg/nuclide-clang-rpc/lib/ClangFlagsManager.js
> +    if (this._clangProjectFlags != null) {
As mentioned above, you need to look this up by `flagsFile`. And you need to cache the promise- see the `getFlagsForSrc` cached vs impl pattern above

2017-02-02 23:13 UTC, hansonw commented on pkg/nuclide-clang-rpc/spec/ClangFlagsManager-spec.js
> +      const tmpJsonFile = nuclideUri.join(__dirname, 'fixtures', 'nuclide_clang_flags.json');
Let's use a real temporary directory for this test. We have a `copyFixture` utility (see https://github.com/facebook/nuclide/blob/648d770f3f58794dbdcfa1b0d9ccf6ae484e1581/spec/clang-refactor-integration-spec.js#L25), so let's copy out the fixtures directory. The temporary directory will be automatically cleaned up so no need for the manual `afterEach` either :)

2017-02-02 23:32 UTC, AlexTalks commented
@hansonw thanks for the feedback!  will fix up your comments and push another commit.

2017-02-03 00:06 UTC, AlexTalks commented on pkg/nuclide-clang-rpc/lib/ClangFlagsManager.js
> +  _clangProjectFlags: ?ClangProjectFlags;
good to know.  I didn't realize how that worked, but of course that makes sense.

2017-02-03 00:49 UTC, AlexTalks commented
@hansonw added the commit.  I'm not sure if @facebook-github-bot expects us to have amended our earlier commits, or have pushed a new commit?  (Also I somewhat assume that arcanist actually squashes the PR before merge or something)

2017-02-03 02:32 UTC, hansonw commented
Good stuff, thanks! Yeah our GitHub -> Phabricator flow will squash all your commits and close this PR. Just going to pass it through internal review first

2017-02-03 06:09 UTC, a20012251 commented
very nice :) We might use it for our project

2017-02-06 22:56 UTC, closed without merging

2017-02-07 11:12 UTC, janosimas commented
Is it already in last nuclide release?
any docs or example on how to crete the config file?

2017-02-07 17:56 UTC, hansonw commented
Yes this is in v0.204! Check the PR for docs (the C++ docs section was updated)

2017-02-14 16:52 UTC, janosimas commented
Hi, I did some tests and couldn't get it to work.

I included -stdlib=libc++ in .nuclide_clang_config.json but the diagnostic still cant find the stdlib.
any tips?

2017-02-14 20:28 UTC, AlexTalks commented
@janosimas an easy way to check it to see the running instances of `clang_server.py` and see what flags it is using for each translation unit.  For me I needed to make sure that the actual paths of the system header files were passed in through `-isystem` include flags.

2017-02-15 09:59 UTC, janosimas commented
@AlexTalks I'm doing some tests here but if I use the flags of the running instance of  the clang_server.py I can compile the file with no warning or error.
Is the clang_server.py behavior different from the clang?

2017-02-15 17:54 UTC, hansonw commented
@janosimas have you seen https://github.com/facebook/nuclide/issues/916? libclang seems to be unaware of the default system header location, so you have to extract them via `clang -### -c <file>`

2017-02-16 12:49 UTC, janosimas commented
After some sweating it worked, for some reason using -isystem for the gcc stdlib didn't work.
I has to install clang stdlib, set -stdlib=libc++ and isystem clangs include folders.