Context View doc
facebook/nuclide pull request #810
Opened 2016-10-14 21:49 UTC by zardra

Fixes #799 

Added Context View doc and updated keyboard shortcuts for the new command.

2016-10-17 18:10 UTC, JoelMarcey requested changes
I had a few comments on this....

2016-10-17 18:10 UTC, JoelMarcey commented on docs/_docs/features/context-view.md
> +> Content View currently supports [Hack](/docs/languages/hack), [Python](/docs/languages/python), and [C++](/docs/languages/cpp) files.
s/Content View/Context View

2016-10-17 18:10 UTC, JoelMarcey commented on docs/_docs/features/context-view.md
> +1. Press Cmd-I (Ctrl-I on Linux).
Should the commands be code formatted?

2016-10-17 18:10 UTC, JoelMarcey commented on docs/_docs/features/context-view.md
> +> Content View currently supports [Hack](/docs/languages/hack), [Python](/docs/languages/python), and [C++](/docs/languages/cpp) files.
The images seem to show Swift code; but Swift isn't listed as one of the languages above. Should Swift be listed here?

2016-10-17 18:21 UTC, modocache commented on docs/_docs/features/context-view.md
> +> Content View currently supports [Hack](/docs/languages/hack), [Python](/docs/languages/python), and [C++](/docs/languages/cpp) files.
+1, although to be clear, the images are of Objective-C.

2016-10-17 18:24 UTC, JoelMarcey commented on docs/_docs/features/context-view.md
> +> Content View currently supports [Hack](/docs/languages/hack), [Python](/docs/languages/python), and [C++](/docs/languages/cpp) files.
Oh, are they? ... oh yeah, I guess they are. Thanks!

2016-10-17 18:44 UTC, zardra commented on docs/_docs/features/context-view.md
> +> Content View currently supports [Hack](/docs/languages/hack), [Python](/docs/languages/python), and [C++](/docs/languages/cpp) files.
Should I specifically list Objective-C as well?

2016-10-17 18:53 UTC, zardra commented
How's it look now?

2016-10-17 19:42 UTC, JoelMarcey commented
@modocache Is Swift also supported too for Context View? Or just Objective-C?

2016-10-17 22:58 UTC, modocache commented
I would be very surprised if Swift was also supported. I don't think it is.

2016-10-21 00:49 UTC, JoelMarcey approved these changes

2016-10-21 01:24 UTC, closed without merging